import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import MainWrapper from "@/components/layout/main-wrapper";
import { cn } from "@/lib/utils";
import Header from "@/components/layout/header";
import ContentWrapper from "@/components/layout/content-wrapper";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body
        className={cn("bg-background font-sans antialiased", fontSans.variable)}
      >
        <MainWrapper>
          <Header />
          <ContentWrapper>{children}</ContentWrapper>
        </MainWrapper>
      </body>
    </html>
  );
}
