import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/Header";
import Aside from "./components/layout/Aside";
import Footer from "./components/layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className="relative">
        {/* <Header /> */}
        <div className="flex gap-5 p-5">
          <Aside />
          <main className="bg-white w-full p-[1rem] rounded">{children}</main>
        </div>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
